### ISSUE TITLE
Create a Terms of Service for Sandcats

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandcats#108]
Overall purpose: Make sure we don't spend money on certs excessively for people who decide to use Sandcats for non-Sandstorm servers.

Strategy:
- Find our existing terms of service for Oasis
- add a new file for sandcats-terms, sandcats-privacy
- make sure it makes sense
- Get review from @kentonv 
- serve those from sandcats.io/terms sandcats.io/privacy

**Comment by kentonv** [comment]
I don't see the purpose of this as being to prevent non-Sandstorm users from using sandcats subdomains. I think the purpose is to clearly define under what circumstances we may cancel someone's service, and other rules that really ought to be spelled out (and may be required to be spelled out, by law...).

In any case I have a pull request here awaiting your review:

https://github.com/sandstorm-io/tos-pp/pull/15

**Comment by paulproteus** [comment]
Indeed. Thanks for doing that; digging into this now.

**Comment by paulproteus** [comment]
This is done now; see https://sandcats.io/privacy etc.
