### ISSUE TITLE
Pinned Grains?

### ISSUE THREAD

**Issue by sambozek** [sandstorm-io/sandcats#154]
When I open sandcats the grains that I had been using in my last instance are cleared from the sidebar. Is there a way to keep various grains pinned to that sidebar? 

### At end of session:
![screen shot 2016-12-09 at 9 41 51 am](https://cloud.githubusercontent.com/assets/13842157/21059781/ff00a124-bdf8-11e6-9593-5d7ad11aaff0.png)

### Start of new session:
![screen shot 2016-12-09 at 9 38 44 am](https://cloud.githubusercontent.com/assets/13842157/21059774/f6ac0cc0-bdf8-11e6-916a-49a02a2d01bf.png)

Thanks.

**Comment by dwrensha** [comment]
There is no way to do this currently. We have an open issue about it over on the Sandstorm repo: https://github.com/sandstorm-io/sandstorm/issues/2585. Closing this as a duplicate.
