### ISSUE TITLE
Change IP address of server

### ISSUE THREAD

**Issue by pnunn** [sandstorm-io/sandcats#166]
Hi Guys,  Very new to sandstorm and it looks really interesting as an alternative to things like nextcloud.

I installed a server using an internal address and forwarding the data through my firewall to port 443 but that wasn't going to work for me long term. 

I changed the IP on the server to a routable address and the GUI seems to have picked up the change (amazingly) and I can log in to the admin console etc., however, when I try and create a new anything I get an error

ui-76bacd2aeb81b155cade5f0c16ce55c0.marketdispatch.sandcats.io didn’t send any data.

I assume its because of the address change.

Can I fix this, or do I blow it away and start again?

**Comment by ocdtrekkie** [comment]
I think all of your dynamic DNS/wildcard DNS should all be squared away (the nice thing about using a Sandcats address), which is why I am sort of wondering if it is possible it is something else. Do you do anything unique with DNS inside your network? Do grains load when you access your server from a device outside your network vs. do they load when you access your server from inside your network? (I've personally had weird quirks with hairpin routing before.)

**Comment by pnunn** [comment]
Hi @ocdtrekkie, thanks for chipping in. No, nothing odd with DNS on my end. The server now has a fully external IP address so should be able to talk. No firewalls. 

I tried from my phone an the mobile network and the same thing happens. I can get to the UI, but no app will server up data it seems.

**Comment by ocdtrekkie** [comment]
That's really weird, anything in the browser console of the system log in the admin panel that looks interesting? Did you manually change anything in sandstorm.conf? And it loaded apps correctly before you moved it?

**Comment by ocdtrekkie** [comment]
Also... is it possible you are using Ubuntu 24.04? https://groups.google.com/g/sandstorm-dev/c/4JFhr7B7QZU (I wouldn't expect this to be the issue if grains were working before you changed the IP address... but it would potentially be a very likely cause if you were using Ubuntu 24.04.

**Comment by pnunn** [comment]
Hi @ocdtrekkie, I am indeed running 24.04. I'm pretty sure things were loading before I moved the IP, but, I'm not 100% sure they were to be honest. I didn't do much testing before I decided it needed to be on its own IP.

However, having applied the patch, and restarting sandstorm, it seems it all working now :). 

Thanks SO much for the help.

**Comment by ocdtrekkie** [comment]
Not a problem... that's a really good nudge I need to get that added to the documentation. :| Shame on me.
