### ISSUE TITLE
Vagrant base box should use systemd init system (or we should stop depending on systemd)

### ISSUE THREAD

**Issue by paulproteus** [sandstorm-io/sandcats#5]
Right now, the Vagrant base box uses sysvinit, but the `vagrant provision` process involves adding a systemd service.

This results in sadness, since we can't really enable the service until after a reboot causes systemd to take over as PID 1.

One workaround would be to convert the systemd service into an init script. I am -0 on that, and +1 on finding a systemd-enabled Vagrant base box.

**Comment by silopolis** [comment]
May I suggest using https://github.com/boxcutter/debian base box ?!

**Comment by zarvox** [comment]
https://atlas.hashicorp.com/debian/boxes/jessie64/ appears to be an official effort, and uses systemd.  I'd encourage us to switch to that, and I hope to do the same for `vagrant-spk` once I've done some testing.

**Comment by paulproteus** [comment]
That sounds like a great idea to me.

I do have some micro hesitations. Actually, just one I guess!

If you want to use systemd units when starting e.g. MySQL within the
Sandstorm grain, I'm tentatively excited but worried systemd won't work in
the Sandstorm sandbox. But I definitely haven't tried it. If it _does_ work
in the Sandstorm sandbox, this is a completely great idea.

P.S. It's probably worth writing a blog post at some point about why we
can't comply with the systemd container specification.

**Comment by zarvox** [comment]
We can't currently use the systemd units to start MySQL within the Sandstorm grain.  But we also can't currently use the sysvinit scripts, nor upstart jobs either.

What we do today is manually invoke `mysqld` from your grain's entrypoint (often a bash script).  That will continue to work, but is not very declarative/reusable.  So this is not a functional regression, just a future opportunity.

It would be cool if someday we could punt service bringup/supervision within the grains to `systemd --user` or something like that.  From talking with some friends, I'm under the impression that systemd does not play nicely inside user namespaces (which we require), without /proc, or some other things that we do to our sandbox, but perhaps that situation will get better over time, or we can run systemd in some feature-limited mode or something.

**Comment by paulproteus** [comment]
Such +1
