### ISSUE TITLE
Enabling ssl

### ISSUE THREAD

**Issue by ltap** [sandstorm-io/sandcats#79]
Hi, how do I enable SSL on my name.sandcats.io?

**Comment by paulproteus** [comment]
Hi @ltap 

For now, your options are:
- Get a wildcard certificate from a vendor like GlobalSign.com https://sslmate.com/ https://cheapsslsecurity.com/sslproducts/wildcardssl.html
- Set up nginx per https://docs.sandstorm.io/en/latest/administering/reverse-proxy/

In the near future, I'd like the Sandstorm/Sandcats system to offer automatic configuration for HTTPS. I'm working on that right now, and hope to have more to say in a week or two.

Let me know if that takes care of your question!

**Comment by paulproteus** [comment]
Hi @ltap ,

There's a new option, documented here. https://docs.sandstorm.io/en/latest/administering/ssl/

Let me know if you try it!

**Comment by ltap** [comment]
This is awesome! Thank you!

**Comment by paulproteus** [comment]
There's a reason I said GlobalSign before. (-:

I'm so excited that you like it! If it's OK, I'll close this issue. Feel free to re-open it if you need further help or this doesn't suit your use-case.
